
import React from 'react'
import Link from 'next/link'
import Head from 'next/head'

const Header = () => {
    return (
        <>
            <Link href="#header" className="arrow-up" title="Up">↑</Link>

            <Head>
                <title>My Portifólio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header id="header">
                <div className="container">

                    <h2>Elvis Farias</h2>
                    <p>Junior Software Engineer</p>

                    <Link
                        href="https://www.linkedin.com/in/elvisfarias/"
                        className="link-linkedin"
                        target='_black'
                        style={{ padding: "4px" }}
                    >
                        <span> Go to Linkedin</span>
                    </Link>

                </div>

            </header>
            <div className="container">
                <nav>
                    <ul style={{display: "flex"}}>
                        <li><Link href="#about">About</Link></li>
                        <li><Link href="#repositoryGit">Repository</Link></li>
                        <li><Link href="https://api.whatsapp.com/send?phone=5549991696698" target="_blank">Contact</Link></li>
                        <li><Link href="#project">Projects</Link></li>
                    </ul>
                </nav>
            </div>
        </>
    )
}

export default Header;
